spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/class
    username: root
    data-password: root
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
server:
    port: 8088
    servlet:
      context-path: /
